kind: Definition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-github
  namespace: default
spec:
  deletionPolicy: Orphan 
  swaggerPath: github.yaml
  resourceGroup: github.com
  resources: 
    # - kind: Gists
    #   identifier: id
    #   verbsDescription:
    #     - action: create
    #       method: POST
    #       path: /gists
    #     - action: get
    #       method: GET
    #       path: /gists/{id}
    - kind: Repo
      identifier: id
      verbsDescription:
        - action: create
          method: POST
          path: /orgs/{org}/repos
        - action: get
          method: GET
          path: /repos/{owner}/{repo}
          altFieldMapping:  # Optional: with the format <newField>: <oldField>
            org: owner
            name: repo