kind: Definition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-nutanix
  namespace: default
spec:
  deletionPolicy: Orphan 
  swaggerPath: nutanix-swagger.yaml
  resourceGroup: nutanix.com
  resources: 
    - kind: Database
      identifier: id
      verbsDescription:
        - action: create
          method: POST
          path: /databases/provision
        - action: get
          method: GET
          path: /databases/{id}