kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: repo-list-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: repo-list-role
  apiGroup: rbac.authorization.k8s.io