kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: repo-list-role
rules:
- apiGroups: ["github.com"]
  resources: ["repoes"]
  verbs: ["*"]
- apiGroups: ["github.com"]
  resources: ["bearerauths"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: ["swaggergen.krateo.io"]
  resources: ["definitions"]
  verbs: ["list"]
- apiGroups: ["github.com"]
  resources: ["repoes/status"]
  verbs: ["*"]
- apiGroups: ["azure.devops.com"]
  resources: ["environmentinstances", "environmentinstances/status", "serviceendpoints", "serviceendpoints/status"]
  verbs: ["*"]
- apiGroups: ["azure.devops.com"]
  resources: ["basicauths"]
  verbs: ["*"]